- hosts: all
  roles:
    - common
    - firefox
    - git
    - i3
    - java
    - javascript
    - laptop
    - mpd
    - polybar
    - syncthing
    - vscodium
  vars:
    network_main_interface: wlp3s0