- name: Install GDM
  aur:
    name:
      - gdm

- name: Configure GDM
  become: yes
  template:
    src: "{{ item }}"
    dest: /etc/gdm/{{ item }}
  with_items:
    - custom.conf

- name: Enable GDM
  become: yes
  systemd:
    name: gdm
    enabled: yes