- name: Disable GDM
  become: yes
  systemd:
    name: gdm
    enabled: no
  ignore_errors: yes

- name: Remove GDM
  package:
    name:
      - gdm
    state: absent

- name: Unconfigure GDM
  become: yes
  file:
    dest: /etc/gdm/custom.conf
    state: absent