- name: Install SDDM
  aur:
    name:
      - chili-sddm-theme
      - sddm

- name: Create SDDM configuration directory
  become: yes
  file:
    dest: /etc/sddm.conf.d
    state: directory

- name: Configure SDDM theme
  become: yes
  copy:
    src: theme.conf
    dest: /etc/sddm.conf.d/theme.conf

- name: Set SDDM user avatar
  become: yes
  get_url:
    url: https://avatars0.githubusercontent.com/u/456645
    dest: /usr/share/sddm/faces/jonjo.face.icon

- name: Enable SDDM
  become: yes
  systemd:
    name: sddm
    enabled: yes