# Path to your oh-my-zsh installation.
export ZSH=$HOME/.config/oh-my-zsh

# Enable automatic updates
zstyle ':omz:update' mode auto

# Enable ZSH plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Enable Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Configure ZSH history
HISTSIZE="100000"
SAVEHIST="100000"
HISTFILE="$HOME/.zsh_history"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY

# Enable Starship (except in Emacs)
if [ -z "$INSIDE_EMACS" ]; then
  eval "$(starship init zsh)"
fi

# Aliases
alias cat='bat -pp'
alias c='xclip -selection clipboard -i'

# Environment
export EDITOR=vim
export GPG_TTY=$(tty)
