- name: Install i3
  become: yes
  package:
    name:
      - dex
      - feh
      - i3-gaps
      - i3lock
      - picom
      - playerctl
      - python-i3ipc
      - xdg-user-dirs
      - xorg-xinit
      - xorg-server

- name: Configure Xorg
  become: yes
  template:
    src: 20-amdgpu.conf
    dest: /etc/X11/xorg.conf.d/20-amdgpu.conf

- name: Configure xinit
  copy:
    src: xinitrc
    dest: $HOME/.xinitrc
    owner: jonjo

- name: Configure X autostart
  copy:
    src: window-manager.zsh
    dest: $HOME/.config/oh-my-zsh/custom/window-manager.zsh
    owner: jonjo

- name: Create i3 configuration directory
  file:
    dest: $HOME/.config/i3
    recurse: yes
    state: directory

- name: Configure i3
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/i3/{{ item }}"
    mode: 0755
  with_items:
    - config
    - picom.conf
    - nextcloud.sh
  register: i3_configured

- name: Copy i3 resources
  copy:
    src: "{{ item }}"
    dest: "$HOME/.config/i3/{{ item }}"
  with_items:
    - background.jpg

- name: Reload i3
  shell: i3-msg reload
  when: i3_configured.changed
