- name: Install Dunst
  become: yes
  package:
    name:
      - dunst
  register: dunst_installed

- name: Create Dunst configuration directory
  file:
    dest: $HOME/.config/dunst
    recurse: yes
    state: directory

- name: Configure Dunst
  copy:
    src: dunstrc
    dest: $HOME/.config/dunst/dunstrc
  register: dunst_configured

- name: Enable Dunst
  systemd:
    name: dunst
    enabled: yes
    daemon_reload: yes
    scope: user

- name: Restart Dunst
  systemd:
    name: dunst
    scope: user
    state: restarted
  # Only restart if the configuration has changed, and if this isn't the initial install (as there's no DISPLAY yet)
  when: dunst_configured.changed and not dunst_installed.changed
