- name: Install keyring packages
  package:
    name:
      - gnome-keyring
      - keepassxc
      - libsecret
  become: yes

- name: Configure ZSH to start the keyring
  copy:
    src: keyring.zsh
    dest: "$HOME/.config/oh-my-zsh/custom"