- name: Install keyring packages
  package:
    name:
      - keepassxc
      - libsecret
  become: yes

- name: Remove old keyring packages
  package:
    name:
      - gnome-keyring
    state: absent

- name: Copy SSH agent script
  copy:
    src: ssh-agent.zsh
    dest: $HOME/.config/oh-my-zsh/custom/ssh-agent.zsh
    mode: 0644
    owner: jonjo

- name: Copy SSH agent systemd unit
  copy:
    src: ssh-agent.service
    dest: $HOME/.config/systemd/user/ssh-agent.service
    mode: 0644
    owner: jonjo

- name: Enable SSH agent
  systemd:
    daemon_reload: yes
    enabled: yes
    name: ssh-agent
    scope: user
    state: started