- name: Configure Pacman
  become: yes
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#{{ item }}'
    line: '{{ item }}'
  with_items:
    - Color
    - TotalDownload
    - CheckSpace
    - VerbosePkgLists

- name: Configure makepkg
  become: yes
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^CFLAGS', line: 'CFLAGS="-march=native -O2 -pipe -fno-plt"' }
    - { regexp: '^CXXFLAGS', line: 'CXXFLAGS="${CFLAGS}"' }
    - { regexp: '^MAKEFLAGS', line: 'MAKEFLAGS="-j{{ ansible_processor_vcpus }}"' }

- name: Install Reflector
  become: yes
  pacman:
    name: reflector

- name: Install Pacman tools
  aur:
    name:
      - yay-bin
  register: pacman_tools_installed

- name: Generate Pacman mirrorlist
  become: yes
  shell: reflector --protocol https --latest 70 --sort rate --save /etc/pacman.d/mirrorlist
  when: pacman_tools_installed.changed
