- name: Install Polybar
  aur:
    name:
      - python-pydbus
      - python-psutil
      - polybar

- name: Create Polybar configuration directory
  file:
    dest: $HOME/.config/polybar
    recurse: yes
    state: directory

- name: Configure Polybar
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/polybar/{{ item }}"
  with_items:
    - bluetooth-battery.py
    - config.0.ini
    - config.1.ini
    - config.bar.ini
    - config.ini
    - launch.sh
    - music.sh
  register: polybar_configured

- name: Make Polybar scripts executable
  file:
    dest: "$HOME/.config/polybar/{{ item }}"
    mode: 0755
  with_items:
    - launch.sh
    - music.sh 
