- name: Install Waybar
  become: yes
  aur:
    name:
      - python-pydbus
      - python-psutil
      - waybar-hyprland-git

- name: Create Waybar configuration directory
  file:
    dest: $HOME/.config/waybar
    recurse: yes
    state: directory

- name: Configure Waybar
  template:
    src: "{{ item }}"
    dest: "$HOME/.config/waybar/{{ item }}"
  with_items:
    - config
    - style.css
    - waybar-media.py
  register: waybar_configured
