- name: Install general packages
  aur:
    name:
      - aria2
      - bind
      - blueman
      - bmon
      - htop
      - iotop
      - jq
      - mpdris2
      - network-manager-applet
      - pulseaudio
      - pulseaudio-bluetooth
      - rsync
      - ttf-dejavu
      - ttf-fira-code
      - ttf-font-awesome
      - whois

- name: Enable Bluetooth
  become: yes
  systemd:
    name: bluetooth
    enabled: yes
    state: started

- name: Create systemd user directory
  file:
    dest: $HOME/.config/systemd/user
    recurse: yes
    state: directory

- name: Copy systemd units
  copy:
    src: "{{ item }}"
    dest: $HOME/.config/systemd/user/{{ item }}
  with_items:
    - blueman-applet.service
    - network-manager-applet.service
  register: systemd_units_copied

- name: Enable systemd units
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    scope: user
    state: "{{ 'restarted' if systemd_units_copied.changed else 'started' }}"
  with_items:
    - blueman-applet.service
    - network-manager-applet.service
    - pulseaudio.service

- name: Create GTK+ configuration directory
  file:
    path: $HOME/.config/gtk-3.0
    state: directory

- name: Configure GTK+
  copy:
    src: "{{ item.src }}"
    dest: $HOME/{{ item.dest }}
  with_items:
    - { src: gtkrc-2.0,   dest: '.gtkrc-2.0' }
    - { src: gtk-3-0.ini, dest: '.config/gtk-3.0/settings.ini' }

- name: Apply sysctl settings
  become: yes
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present

- name: Enable NTP time syncing
  become: yes
  shell: timedatectl set-ntp true