- name: Install Sway
  become: yes
  package:
    name:
      - grim
      - playerctl
      - slurp
      - sway
      - swayidle
      - swaylock
      - xorg-server-xwayland

- name: Create Sway configuration directory
  file:
    dest: $HOME/.config/sway
    recurse: yes
    state: directory

- name: Configure Sway
  copy:
    src: "{{ item }}"
    dest: "$HOME/.config/sway/{{ item }}"
  with_items:
    - background.jpg
    - config
    - fader.py
  register: sway_configured

- name: Copy Sway systemd target
  copy:
    src: sway-session.target
    dest: $HOME/.config/systemd/user/sway-session.target

- name: Configure ZSH to start Sway
  copy:
    src: sway.zsh
    dest: "$HOME/.config/oh-my-zsh/custom"

- name: Reload Sway
  shell: swaymsg reload
  when: sway_configured.changed